Cproductofacundo
andreybejaranodh/recuperatorio-pju11 pull request #14
Opened 2024-06-16 22:17 UTC by deotrolado

Crear controlador para crear un Categoria de producto y retornar todas las categorias de producto

2024-06-16 23:39 UTC, andreybejaranodh commented on src/controllers/api/productCategoryController.js
>  const db = require('../../database/models');
Esta bien este controlador, puede q te salga conflicto cuando cambies lo q te dije en el otro PR, arregla lo del otro PR despues te digo como solucionar este

2024-06-18 19:40 UTC, deotrolado commented
profe ya cambie lo que me dijo del otro PR

2024-06-19 01:32 UTC, andreybejaranodh submitted a review, later dismissed

2024-06-19 01:33 UTC, andreybejaranodh approved these changes

2024-06-19 01:34 UTC, andreybejaranodh submitted a review, later dismissed
Buen trabajo

2024-06-19 01:41 UTC, andreybejaranodh requested changes
hola, hace un pull checkout de este brach osea, hace lo siguiente:
- git checkout cproductofacundo
- despues hace un git pull
- luego tenes q crear las rutas q estan en `src/routers/api/productCategory.js`
- despues hace el git add y despues el git commit y el push, solo te falta eso, de resto esta bien

2024-06-19 01:43 UTC, andreybejaranodh commented
No hagas los q te dije, los hiciste en el otro pr, la idea es q en cada pr solo se deben trabajar cosas de la tarea, no mezclar porque se confunden las cosas, lo voy a aprovar

2024-06-19 01:43 UTC, andreybejaranodh approved these changes

2024-06-19 01:44 UTC, merged